-- Role rebrand migration: TENANT→BUYER, LANDLORD→MERCHANT, AGENT→MARKETER
-- Run after backing up your database: psql $DATABASE_URL -f prisma/sql/role-rebrand-migration.sql

BEGIN;

-- UserRole
ALTER TYPE "UserRole" RENAME VALUE 'BUYER' TO 'BUYER';
ALTER TYPE "UserRole" RENAME VALUE 'MERCHANT' TO 'MERCHANT';
ALTER TYPE "UserRole" RENAME VALUE 'MARKETER' TO 'MARKETER';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'COMPLIANCE_OFFICER';

-- WalletType
ALTER TYPE "WalletType" RENAME VALUE 'BUYER' TO 'BUYER';
ALTER TYPE "WalletType" RENAME VALUE 'MERCHANT' TO 'MERCHANT';
ALTER TYPE "WalletType" RENAME VALUE 'MARKETER' TO 'MARKETER';

-- BeneficiaryType
ALTER TYPE "BeneficiaryType" RENAME VALUE 'MERCHANT' TO 'MERCHANT';
ALTER TYPE "BeneficiaryType" RENAME VALUE 'MARKETER' TO 'MARKETER';

COMMIT;
