-- Role rebrand migration: TENANT→BUYER, LANDLORD→MERCHANT, AGENT→MARKETER
-- Windows (Docker): npm run db:role-rebrand
-- Or: psql $DATABASE_URL -f prisma/sql/role-rebrand-migration.sql

BEGIN;

-- UserRole
ALTER TYPE "UserRole" RENAME VALUE 'TENANT' TO 'BUYER';
ALTER TYPE "UserRole" RENAME VALUE 'LANDLORD' TO 'MERCHANT';
ALTER TYPE "UserRole" RENAME VALUE 'AGENT' TO 'MARKETER';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'COMPLIANCE_OFFICER';

-- WalletType
ALTER TYPE "WalletType" RENAME VALUE 'TENANT' TO 'BUYER';
ALTER TYPE "WalletType" RENAME VALUE 'LANDLORD' TO 'MERCHANT';
ALTER TYPE "WalletType" RENAME VALUE 'AGENT' TO 'MARKETER';

-- BeneficiaryType
ALTER TYPE "BeneficiaryType" RENAME VALUE 'LANDLORD' TO 'MERCHANT';
ALTER TYPE "BeneficiaryType" RENAME VALUE 'AGENT' TO 'MARKETER';

COMMIT;
